services:
  # Apache service with Laravel and Vue
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_apache
    volumes:
      - .:/var/www/html
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"
    networks:
      - laravel

  # MySQL database
  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel

networks:
  laravel:


volumes:
  mysql_data:
