services:
    app:
        build:
            context: .
            dockerfile: docker/production/php/Dockerfile
        image: software-spmi-apache:latest
        container_name: spmi-app
        restart: unless-stopped
        environment:
            APP_ENV: production
            APP_DEBUG: "${APP_DEBUG}"
            APP_KEY: "${APP_KEY}"
            DB_CONNECTION: "${DB_CONNECTION}"
            DB_HOST: "${DB_HOST}"
            DB_PORT: "${DB_PORT}"
            DB_DATABASE: "${DB_DATABASE}"
            DB_USERNAME: "${DB_USERNAME}"
            DB_PASSWORD: "${DB_PASSWORD}"
            TRUSTED_PROXIES: "${TRUSTED_PROXIES}"
            SESSION_DRIVER: "${SESSION_DRIVER}"
            SESSION_SECURE_COOKIE: "${SESSION_SECURE_COOKIE}"
            SESSION_DOMAIN: "${SESSION_DOMAIN}"
            SESSION_SAME_SITE: "${SESSION_SAME_SITE}"
            SESSION_LIFETIME: "${SESSION_LIFETIME}"
            ASSET_URL: "${ASSET_URL}"
            APP_URL: "${APP_URL}"
        user: root
        ports:
            - "${APP_PORT:-8081}:80"
        depends_on:
            mysql:
                condition: service_healthy
        entrypoint: 
            - sh
            - -c
            - |
              rm -rf bootstrap/cache/*.php
              chmod -R 777 storage bootstrap/cache
              php artisan config:clear
              php artisan migrate --force || exit 1
              apache2-foreground
        volumes:
            - spmi-storage:/var/www/html/storage
        networks:
            - spmi-network
 
    mysql:
        image: 'mysql:8.4'
        container_name: spmi-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - spmi-mysql:/var/lib/mysql
        networks:
            - spmi-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

networks:
    spmi-network:
        driver: bridge

volumes:
    spmi-mysql:
    spmi-redis:
    spmi-storage: